POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Plii plaa pllooooo",
    "date": "11.3.1230",
    "important": "true",
    "userId": "5d14c3757a87488aa0397724"
}